# Api que esta rodando, v1 mais estavel
apiVersion: v1
# O que quero rodar
kind: Pod
# Informações relacionadas ao pod
metadata:
  # São pares de chave-valor que podem ser usados para identificar e selecionar objetos Kubernetes
  labels:
    run: giropops
  # nome do pod
  name: emptydir
# Especificações do pod
spec:
  containers:
  # Imagem
  - image: nginx
    # Nome do container
    name: webserver
    # Lista de pontos de montagem para volumes nos contêineres.
    volumeMounts:
    # Ponto de montagem dentro do contêiner.
    - mountPath: /giropops
      # Nome do volume a ser montado.
      name: primeiro-emptydir
    # Limitação de recursos
    resources:
      # Limites máximos de recursos que o container pode consumir.
      limits:
        cpu: "1"
        memory: "128Mi"
      # Recursos mínimos que o container precisa para ser executado corretamente
      requests:
        cpu: "0.5"
        memory: "64Mi"
    
  # Define a política DNS para o Pod. "ClusterFirst" indica que o DNS do cluster deve ser consultado primeiro
  dnsPolicy: ClusterFirst
  # Define a política de reinicialização do Pod. "Always" indica que o Pod deve ser reiniciado sempre que falhar
  restartPolicy: Always
  # Lista de volumes disponíveis para montagem nos contêineres.
  volumes:
  # Nome do volume que será criado e montado.
  - name: primeiro-emptydir
    # Tipo de volume: diretório vazio.
    emptyDir:
      # Limite de tamanho do diretório vazio (256 megabytes).
      sizeLimit: 256Mi