apiVersion: v1 # Indica a versão da API Kubernetes que está sendo usada.
kind: Pod # Define o tipo de recurso, neste caso, é um Pod.
metadata: # Metadados para identificar e descrever o recurso.
  labels: # Etiquetas para identificar o Pod.
    run: giropops # Etiqueta "run" com o valor "giropops".
  name: emptydir # Nome do Pod, neste caso, é "emptydir".
spec: # Especificação do Pod.
  containers: # Lista de contêineres no Pod.
  - image: nginx # Primeiro contêiner: usa a imagem do nginx.
    name: webserver # Nome do primeiro contêiner.
    volumeMounts: # Pontos de montagem do volume para o primeiro contêiner.
    - mountPath: /giropops # Caminho de montagem no contêiner.
      name: primeiro-emptydir # Nome do volume a ser montado.
    resources: # Recursos alocados para o primeiro contêiner.
      limits: # Limites máximos de recursos que o contêiner pode usar.
        cpu: "1" # Limite máximo de uso de CPU.
        memory: "128Mi" # Limite máximo de uso de memória.
      requests: # Recursos mínimos que o contêiner precisa.
        cpu: "0.5" # Quantidade mínima de CPU necessária.
        memory: "64Mi" # Quantidade mínima de memória necessária.

  - image: redis # Segundo contêiner: usa a imagem do redis.
    name: redis # Nome do segundo contêiner.
    volumeMounts: # Pontos de montagem do volume para o segundo contêiner.
    - mountPath: /redis # Caminho de montagem no contêiner.
      name: primeiro-emptydir # Nome do volume a ser montado.
    resources: # Recursos alocados para o segundo contêiner.
      limits: # Limites máximos de recursos que o contêiner pode usar.
        cpu: "1" # Limite máximo de uso de CPU.
        memory: "256Mi" # Limite máximo de uso de memória.
      requests: # Recursos mínimos que o contêiner precisa.
        cpu: "0.5" # Quantidade mínima de CPU necessária.
        memory: "128Mi" # Quantidade mínima de memória necessária.

  dnsPolicy: ClusterFirst # Política de DNS para o Pod.
  restartPolicy: Always # Política de reinicialização do Pod (sempre reiniciar em caso de falha).
  volumes: # Lista de volumes a serem usados pelo Pod.
  - name: primeiro-emptydir # Nome do volume.
    emptyDir: # Tipo de volume EmptyDir.
      sizeLimit: 256Mi # Limite de tamanho do volume EmptyDir.
