# Api que esta rodando, v1 mais estavel
apiVersion: v1
# O que quero rodar
kind: Pod
# Informações relacionadas ao pod
metadata:
  # São pares de chave-valor que podem ser usados para identificar e selecionar objetos Kubernetes
  labels:
    run: girus
    service: webserver
  # nome do pod
  name: girus
# Especificações do pod
spec:
  containers:
  # Imagem
  - image: nginx
    # Nome do container
    name: girus
    # Limitação de recursos
    resources: {}

  - image: busybox
    name: busybox
    # Especificar os argumentos que serão passados para o comando principal do container quando ele for iniciado
    args: 
    - sleep
    - "600"
    
    
    resources: {}


  # Define a política DNS para o Pod. "ClusterFirst" indica que o DNS do cluster deve ser consultado primeiro
  dnsPolicy: ClusterFirst
  # Define a política de reinicialização do Pod. "Always" indica que o Pod deve ser reiniciado sempre que falhar
  restartPolicy: Always
