# Versão da API que está sendo controlada
apiVersion: v1

# Tipo de recurso que está sendo criado (nesse caso, um Pod)
kind: Pod

# Metadados do Pod, incluindo nome e rótulos
metadata:
  # Rótulos atribuídos ao Pod, identificado como "nginx"
  labels:
    run: nginx
  # Nome do Pod é "nginx"
  name: nginx

# Especificações do Pod, incluindo contêineres
spec:
  # Lista de contêineres no Pod
  containers:
  - 
    # Imagem usada para o contêiner
    image: nginx
    # Nome do contêiner é "nginx"
    name: nginx
    # Porta que o contêiner está expondo (porta 80)
    ports:
    - containerPort: 80
    # Recursos alocados para o contêiner (nenhum especificado)
    resources: {}

  # Política DNS do Pod (ClusterFirst)
  dnsPolicy: ClusterFirst
  # Política de reinicialização do Pod (Always)
  restartPolicy: Always
