apiVersion: apps/v1  # Versão da API do Kubernetes utilizada para criar este recurso.
kind: Deployment  # Tipo de recurso do Kubernetes responsável por gerenciar um conjunto de réplicas de um aplicativo.
metadata:  # Metadados do Deployment.
  labels:  # Rótulos aplicados ao Deployment para identificação.
    app: nginx-deployment  # Rótulo "app" com o valor "nginx-deployment".
  name: nginx-deployment  # Nome do Deployment.
spec:  # Especificações do Deployment.
  replicas: 1  # Número de réplicas desejadas para o aplicativo.
  selector:  # Seleciona os pods gerenciados por este Deployment.
    matchLabels:  # Define as correspondências de rótulos para selecionar os pods.
      app: nginx-deployment  # Corresponde ao rótulo "app" com o valor "nginx-deployment".
  strategy: {}  # Estratégia de atualização do Deployment (não especificada neste caso, o que significa que será usado o padrão).

  template:  # Template para os pods gerados pelo Deployment.
    metadata:  # Metadados do pod template.
      labels:  # Rótulos aplicados aos pods criados.
        app: nginx-deployment  # Rótulo "app" com o valor "nginx-deployment".
    spec:  # Especificações do pod template.
      containers:  # Lista de containers no pod.
        - name: nginx-deployment  # Nome do container.
          image: nginx:1.19  # Imagem do container a ser usada.
          resources:  # Recursos de computação atribuídos ao container.
            limits:  # Limites máximos de recursos que o container pode usar.
              cpu: "0.5"  # Limite máximo de uso de CPU pelo container.
              memory: 256Mi  # Limite máximo de uso de memória pelo container.
            requests:  # Recursos mínimos requeridos pelo container.
              cpu: "0.25"  # Quantidade mínima de CPU solicitada pelo container.
              memory: 128Mi  # Quantidade mínima de memória solicitada pelo container.
          livenessProbe:  # Sonda de verificação de integridade do pod.
            tcpSocket:  # Tipo de sonda que verifica a disponibilidade de uma porta TCP.
              port: 80  # Porta TCP a ser verificada.
            initialDelaySeconds: 10  # Tempo em segundos antes da primeira verificação de sonda.
            periodSeconds: 10  # Intervalo em segundos entre as verificações de sonda.
            timeoutSeconds: 5  # Tempo máximo em segundos permitido para a sonda verificar o pod.
            failureThreshold: 3  # Número de falhas consecutivas da sonda antes de marcar o pod como falho.
