apiVersion: v1  # Versão da API do Kubernetes para o recurso PersistentVolume
kind: PersistentVolume  # Tipo de recurso sendo definido, neste caso, um PersistentVolume
metadata:  # Metadados do recurso
  labels:  # Etiquetas para identificar o recurso
    storage: nfs  # Etiqueta "storage" com valor "nfs"
  name: meu-pv-nfs  # Nome do PersistentVolume, neste caso, "meu-pv-nfs"
spec:  # Especificações do PersistentVolume
  capacity:  # Capacidade do volume
    storage: 1Gi  # Tamanho de armazenamento disponível, neste caso, 1 gigabyte (Gi)
  accessModes:  # Modos de acesso ao volume
    - ReadWriteOnce  # Modo de acesso, que neste caso é "ReadWriteOnce"
  persistentVolumeReclaimPolicy: Retain  # Política de recuperação do volume, que neste caso é "Retain"
  nfs:  # Configurações específicas para volumes NFS
    path: "/mnt/nfs"  # Caminho do NFS no servidor
    server: 192.168.1.119  # Endereço IP do servidor NFS
  storageClassName: giropops  # Nome da classe de armazenamento a ser usado pelo PersistentVolume
