apiVersion: v1  # Define a versão da API que está sendo usada. Neste caso, é a versão "v1" da API do Kubernetes.
data:
  nginx.conf: |  # Define a chave "nginx.conf" que contém o conteúdo do arquivo de configuração do Nginx.
  
    events{ }  # Seção "events" da configuração do Nginx, geralmente usada para configurar eventos de conexão.

    http{  # Seção "http" da configuração do Nginx, onde são definidas as configurações HTTP.
      server{  # Seção "server" que define um servidor virtual.
        listen 80;  # Configura o servidor para escutar na porta 80 (HTTP).
        listen 443 ssl;  # Configura o servidor para escutar na porta 443 (HTTPS) com SSL.
        ssl_certificate /etc/nginx/tls/certificado.crt;  # Especifica o caminho do certificado SSL.
        ssl_certificate_key /etc/nginx/tls/chave-privada.key;  # Especifica o caminho da chave privada SSL.

        location / {  # Configura um bloco de localização para a raiz do servidor.
          return 200 'Ola\n';  # Retorna a resposta "Ola\n" com o status 200 OK.
          add_header Content-Type text/plain;  # Adiciona um cabeçalho de resposta para definir o tipo de conteúdo como "text/plain".
        } 
      }
    }

kind: ConfigMap  # Especifica o tipo de objeto que está sendo criado. Aqui, estamos criando um objeto do tipo "ConfigMap".
metadata:
  name: nginx-conf  # Define o nome do ConfigMap, que é "nginx-conf".
  namespace: default  # Define o namespace onde o ConfigMap será criado. Aqui, estamos usando o namespace "default".
