apiVersion: v1
kind: Secret
metadata:
  name: dockerhub-test
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: |
    ewoJImF1dGhzIjogewoJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CgkJCSJhdXRoIjogImF6QmtlVHBrWTJ0eVgzQmhkRjlzWlhwelFrdFZOVGhSZUVkWlduQllXa0ZwTjBKbllqaE5jMmM9IgoJCX0KCX0KfQ==