apiVersion: v1  # Define a versão da API que está sendo usada. Neste caso, é a versão "v1" da API do Kubernetes.
kind: Secret # Especifica o tipo de objeto que está sendo criado. Aqui, estamos criando um objeto do tipo "Secret".
metadata:
  name: dockerhub-test  # Metadados que identificam o Secret. "name" define o nome do Secret, que é "dockerhub-test".

type: kubernetes.io/dockerconfigjson   # Define o tipo do Secret. "kubernetes.io/dockerconfigjson" indica que este Secret armazena credenciais Docker.
 
data: # Define os dados do Secret. O campo ".dockerconfigjson" contém o arquivo config.json do Docker codificado em base64.

  .dockerconfigjson: |  # Substitua o valor pelo conteúdo codificado em base64 do seu arquivo ~/.docker/config.json.
    