apiVersion: v1  # Define a versão da API que está sendo usada. Neste caso, é a versão "v1" da API do Kubernetes.
kind: Pod  # Especifica o tipo de objeto que está sendo criado. Aqui, estamos criando um objeto do tipo "Pod".
metadata:
  name: giropops-pod  # Define o nome do Pod, que é "giropops-pod".
  labels:
    app: nginx  # Adiciona um rótulo ao Pod. O rótulo "app: nginx" pode ser usado para selecionar este Pod em operações de Kubernetes.
spec:
  containers:
    - name: giropops-container  # Define o nome do container dentro do Pod, que é "giropops-container".
      image: nginx  # Especifica a imagem Docker que será usada para o container. Neste caso, a imagem é "nginx".
      ports:
        - containerPort: 80  # Abre a porta 80 no container, geralmente usada para HTTP.
        - containerPort: 443  # Abre a porta 443 no container, geralmente usada para HTTPS.
      volumeMounts:
        - mountPath: /etc/nginx/nginx.conf  # Define o caminho no container onde o volume será montado. Aqui, estamos montando o arquivo de configuração do Nginx.
          name: nginx-config-volume  # Refere-se ao volume chamado "nginx-config-volume", que será definido abaixo.
          subPath: nginx.conf  # Define o subcaminho dentro do volume que será montado. Neste caso, é o arquivo "nginx.conf".
        - name: nginx-tls  # Refere-se ao volume chamado "nginx-tls", que será definido abaixo.
          mountPath: /etc/nginx/tls  # Define o caminho no container onde o volume será montado. Aqui, estamos montando o diretório para os arquivos TLS.
  volumes:
    - name: nginx-config-volume  # Define um volume chamado "nginx-config-volume".
      configMap:
        name: nginx-conf  # Especifica que este volume é um ConfigMap chamado "nginx-conf".
    - name: nginx-tls  # Define um volume chamado "nginx-tls".
      secret:
        secretName: meu-servico-web-tls  # Especifica que este volume é um Secret chamado "meu-servico-web-tls".
        items:
          - key: tls.crt  # Define a chave "tls.crt" do Secret.
            path: certificado.crt  # Define o caminho onde a chave "tls.crt" será montada no container.
          - key: tls.key  # Define a chave "tls.key" do Secret.
            path: chave-privada.key  # Define o caminho onde a chave "tls.key" será montada no container.
