apiVersion: v1
kind: Pod
metadata:
  name: giropops-pod
  labels:
    app: nginx
spec:
  containers:
    - name: giropops-container
      image: nginx
      ports:
        - containerPort: 80
        - containerPort: 443
      volumeMounts:
        - mountPath: /etc/nginx/nginx.conf
          name: nginx-config-volume
          subPath: nginx.conf
        - name: nginx-tls
          mountPath: /etc/nginx/tls
  volumes:
    - name: nginx-config-volume
      configMap:
        name: nginx-conf
    - name: nginx-tls
      secret:
        secretName: meu-servico-web-tls
        items:
          - key: tls.crt
            path: certificado.crt
          - key: tls.key
            path: chave-privada.key