apiVersion: v1
kind: Pod
metadata:
  name: giropops-pod
spec:
  containers:
    - name: giropops-container
      image: nginx
      env:
        - name: USERNAME
          valueFrom:
            secretKeyRef:
              key: username
              name: giropops-secrets
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: giropops-secrets