apiVersion: v1  # Define a versão da API que está sendo usada. Neste caso, é a versão "v1" da API do Kubernetes.
kind: Pod  # Especifica o tipo de objeto que está sendo criado. Aqui, estamos criando um objeto do tipo "Pod".
metadata:
  name: giropops-pod  # Define o nome do Pod, que é "giropops-pod".
spec:
  containers:  # Define a lista de containers que serão executados no Pod.
    - name: giropops-container  # Nome do container dentro do Pod.
      image: nginx  # Especifica a imagem do container. Neste caso, é a imagem do Nginx.
      env:  # Define as variáveis de ambiente para o container.
        - name: USERNAME  # Nome da variável de ambiente.
          valueFrom:  # Especifica que o valor da variável será obtido de outra fonte.
            secretKeyRef:  # Refere-se a uma chave específica dentro de um Secret do Kubernetes.
              key: username  # A chave dentro do Secret que contém o valor para a variável "USERNAME".
              name: giropops-secrets  # O nome do Secret onde a chave "username" está armazenada.
        - name: PASSWORD  # Nome da variável de ambiente.
          valueFrom:  # Especifica que o valor da variável será obtido de outra fonte.
            secretKeyRef:  # Refere-se a uma chave específica dentro de um Secret do Kubernetes.
              key: password  # A chave dentro do Secret que contém o valor para a variável "PASSWORD".
              name: giropops-secrets  # O nome do Secret onde a chave "password" está armazenada.
