apiVersion: v1  # Define a versão da API do Kubernetes que estamos usando
kind: Pod  # Especifica que o objeto a ser criado é um Pod
metadata:
  name: nginx-pod  # Nome do Pod
  labels:
    app: nginx-pod  # Rótulo do Pod, útil para seleção e organização
spec:
  containers:  # Lista dos containers que serão executados neste Pod
    - name: nginx  # Nome do primeiro container
      image: nginx  # Imagem Docker usada para este container
      ports:
        - containerPort: 80  # Expõe a porta 80 no container
          name: http  # Nome da porta exposta
      volumeMounts:
        - mountPath: /etc/nginx/conf.d/default.conf  # Caminho no container onde o volume será montado
          name: nginx-config  # Nome do volume a ser montado
          subPath: nginx.conf  # Caminho específico dentro do volume (subPath) para o arquivo nginx.conf
    - name: nginx-exporte  # Nome do segundo container
      image: 'nginx/nginx-prometheus-exporter:0.11.0'  # Imagem Docker usada para este container
      args:
      - '-nginx.scrape-uri=http://localhost/metrics'  # Argumentos passados para o container (URL de scrape do NGINX)
      resources:
        limits:
          memory: 128Mi  # Limite de memória para este container
          cpu: 0.3  # Limite de CPU para este container
      ports:
        - containerPort: 9113  # Expõe a porta 9113 no container
          name: metrics  # Nome da porta exposta
  volumes:  # Define os volumes que serão usados pelos containers
    - name: nginx-config  # Nome do volume
      configMap:
        defaultMode: 420  # Permissões padrão do volume montado
        name: nginx-config  # Nome do ConfigMap usado como fonte para este volume
