apiVersion: v1  # Define a versão da API do Kubernetes que estamos usando
kind: ConfigMap  # Especifica que o objeto a ser criado é um ConfigMap
metadata:
  name: nginx-config  # Nome do ConfigMap
data:
  nginx.conf: |
    server {
      listen 80;
      location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
      }
      location /metrics {
        stub_status on;
        access_log off;     
      }

    }