apiVersion: apps/v1  # Define a versão da API do Kubernetes que estamos usando
kind: Deployment  # Especifica que o objeto a ser criado é um Deployment
metadata:
  name: nginx-server  # Nome do Deployment
spec:
  selector:
    matchLabels:
      app: nginx  # Seleciona os Pods que correspondem a este label (app: nginx)
  replicas: 3  # Define o número de réplicas do Pod (neste caso, 3)
  template:
    metadata:
      labels:
        app: nginx  # Aplica o label 'app: nginx' aos Pods criados por este template
      annotations:
        prometheus.io/scrape: 'true'  # Anotação para o Prometheus coletar métricas deste Pod
        prometheus.io/port: '9113'  # Porta onde o Prometheus deve coletar métricas
    spec:
      containers:  # Lista dos containers que serão executados neste Pod
        - name: nginx  # Nome do primeiro container
          image: nginx  # Imagem Docker usada para este container
          ports:
            - containerPort: 80  # Expõe a porta 80 no container
              name: http  # Nome da porta exposta
          volumeMounts:
            - mountPath: /etc/nginx/conf.d/default.conf  # Caminho no container onde o volume será montado
              name: nginx-config  # Nome do volume a ser montado
              subPath: nginx.conf  # Caminho específico dentro do volume (subPath) para o arquivo nginx.conf
        - name: nginx-exporte  # Nome do segundo container
          image: 'nginx/nginx-prometheus-exporter:0.11.0'  # Imagem Docker usada para este container
          args:
            - '-nginx.scrape-uri=http://localhost/metrics'  # Argumentos passados para o container (URL de scrape do NGINX)
          resources:
            limits:
              memory: 128Mi  # Limite de memória para este container
              cpu: 0.3  # Limite de CPU para este container
          ports:
            - containerPort: 9113  # Expõe a porta 9113 no container
              name: metrics  # Nome da porta exposta
      volumes:  # Define os volumes que serão usados pelos containers
        - name: nginx-config  # Nome do volume
          configMap:
            defaultMode: 420  # Permissões padrão do volume montado
            name: nginx-config  # Nome do ConfigMap usado como fonte para este volume
